CXXFLAGS=-Wall	-g	-DNDEBUG

all:
	g++	 bootstrap.cpp -o bootstrap
clean:
	-rm	-f	bootstrap
#-Wall: enable all warnings
#-g: add debug symbols(inorder to use gdb symbols)
#-o: name of the of the output files to create
#-c: do not link
